version: 2.1
jobs:
  build:
    docker:
      - image: python:3-slim
    steps:
      - checkout
      - run: pip install ansible ansible-lint==5.4.0
      - run: ansible-lint --version
      - run: ansible-lint .
