---
- name: Create systemd-tmpfiles
  ansible.builtin.command: /usr/bin/systemd-tmpfiles --prefix=/sys --create
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
