---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: fedora:latest
    privileged: true
    command: /bin/bash -c "while true; do sleep 30; done"
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
