---
- name: Start and enable sshd
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true
  when: enable_sshd

- name: Start and enable fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
  when: enable_fail2ban
