---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/{{ local_user }}/.config/alacritty
    state: directory
    owner: "{{ local_user }}"
    group: wheel
    mode: "0755"

- name: Template alacritty.yml
  ansible.builtin.copy:
    src: templates/alacritty.yml
    dest: /home/{{ local_user }}/.config/alacritty/alacritty.yml
    owner: "{{ local_user }}"
    group: wheel
    mode: "0644"

- name: Stat alacritty.desktop
  ansible.builtin.stat:
    path: /home/{{ local_user }}/.local/share/applications/alacritty.desktop
  register: alacritty_desktop

- name: Template alacritty.desktop
  ansible.builtin.copy:
    src: templates/gnome_desktop/alacritty.desktop
    dest: /home/{{ local_user }}/.local/share/applications/alacritty.desktop
    owner: "{{ local_user }}"
    group: wheel
    mode: "0644"
  when: not alacritty_desktop.stat.exists

- name: Stat Alacritty Desktop Icon
  ansible.builtin.stat:
    path: /usr/share/applications/Alacritty.desktop
  register: alacritty_stat

- name: Disable Alacritty Built-in icon
  become: true
  ansible.builtin.command: mv /usr/share/applications/Alacritty.desktop /usr/share/applications/Alacritty.desktop.not
  when: alacritty_stat.stat.exists

- name: Stat Gnome Terminal Desktop Icon
  ansible.builtin.stat:
    path: /usr/share/applications/org.gnome.Terminal.desktop
  register: gnome_terminal_stat

- name: Disable Gnome-Terminal Built-in icon
  become: true
  ansible.builtin.command: mv /usr/share/applications/org.gnome.Terminal.desktop /usr/share/applications/org.gnome.Terminal.desktop.not
  when: gnome_terminal_stat.stat.exists
