---
- name: Clone Auto-CPUFreq
  ansible.builtin.git:
    repo: https://github.com/AdnanHodzic/auto-cpufreq.git
    dest: /tmp/autocpu
    version: master

- name: Install Auto-CPUFreq dependencies
  ansible.builtin.package:
    name:
      - python3-devel
      - dmidecode
    state: present

- name: Install Python requirements for Auto-CPUFreq
  ansible.builtin.pip:
    requirements: /tmp/autocpu/requirements.txt

- name: Compile Auto-CPUFreq with Python
  ansible.builtin.command:
    cmd: python3 setup.py install --record files.txt
    chdir: /tmp/autocpu

- name: Create auto-cpufreq directory
  ansible.builtin.file:
    path: /usr/local/share/auto-cpufreq/
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Copy scripts for Auto-CPUFreq
  ansible.builtin.copy:
    src: /tmp/autocpu/scripts/
    dest: /usr/local/share/auto-cpufreq/
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  become: true
