---
- name: Remove legacy Docker packages
  ansible.builtin.package:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
    state: absent
  become: true
  tags: [third_party, docker]

- name: Install Podman/Docker compatibility packages
  ansible.builtin.package:
    name:
      - podman-docker
      - docker-compose
    state: present
  become: true
  tags: [third_party, docker]

- name: Disable Docker-Podman warnings (idempotent)
  ansible.builtin.file:
    path: /etc/containers/nodocker
    state: touch
    owner: root
    group: root
    mode: '0644'
  become: true
  tags: [third_party, docker]
