---
- name: Remove Old Docker Agents
  ansible.builtin.package:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
    state: absent

- name: Install Podman Docker
  ansible.builtin.package:
    name:
      - podman-docker
      - docker-compose
    state: present

- name: Disable Docker-Podman Warnings
  ansible.builtin.command: touch /etc/containers/nodocker
  become: true
