---
- name: Import Google Cloud signing keys
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - https://packages.cloud.google.com/yum/doc/yum-key.gpg
    - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  become: true
  tags: [third_party, gcloud]

- name: Check if Google Cloud repo file exists
  ansible.builtin.stat:
    path: /etc/yum.repos.d/google-cloud-sdk.repo
  register: gcloud_repo
  tags: [third_party, gcloud]

- name: Add Google Cloud SDK repository
  ansible.builtin.yum_repository:
    name: google-cloud-sdk
    description: Google Cloud SDK
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64
    gpgcheck: true
    repo_gpgcheck: false
    enabled: true
  when: not gcloud_repo.stat.exists
  become: true
  tags: [third_party, gcloud]

- name: Install Google Cloud SDK packages
  ansible.builtin.dnf:
    name:
      - google-cloud-sdk
      - kubectl
    state: present
  become: true
  tags: [third_party, gcloud]
