- name: HashiCorp Signing Keys
  rpm_key:
    state: present
    key: "{{ item }}"
  become: true
  with_items:
  - https://packages.cloud.google.com/yum/doc/yum-key.gpg
  - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Add Google Cloud Repo
  yum_repository:
    name: gcloud
    description: Google Cloud Repo
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
    gpgcheck: yes

- name: Install Google Cloud SDK
  package:
    name:
      - google-cloud-sdk
      - kubectl
    state: present
