- name: Check for Wine
  ansible.builtin.stat:
    path: /usr/bin/wine
  register: wine_installed
  tags: [third_party, lutris]

- name: Check for Lutris
  ansible.builtin.stat:
    path: /usr/bin/lutris
  register: lutris_installed
  tags: [third_party, lutris]

- name: Install Wine
  ansible.builtin.package:
    name: wine
    state: present
  when: not wine_installed.stat.exists
  become: true
  tags: [third_party, lutris]

- name: Install Lutris
  ansible.builtin.package:
    name: lutris
    state: present
  when: not lutris_installed.stat.exists
  become: true
  tags: [third_party, lutris]

- name: Install Vulkan Loader
  ansible.builtin.package:
    name:
      - vulkan-loader
      - vulkan-loader.i686
    state: present
  when: not lutris_installed.stat.exists
  become: true
  tags: [third_party, lutris]

- name: Install missing 32/64 bit libraries for Lutris
  ansible.builtin.package:
    name:
      - freetype
      - freetype.i686
      - gnutls
      - gnutls.i686
      - gnutls-devel
      - gnutls-devel.i686
      - openldap
      - openldap.i686
      - openldap-devel
      - openldap-devel.i686
      - libgpg-error
      - libgpg-error.i686
      - sqlite2.i686
      - sqlite2.x86_64
    state: present
  when: not lutris_installed.stat.exists
  become: true
  tags: [third_party, lutris]
---
- name: Check for Wine
  ansible.builtin.stat:
    path: /usr/bin/wine
  register: wine_installed
  tags: [third_party, lutris]

- name: Check for Lutris
  ansible.builtin.stat:
    path: /usr/bin/lutris
  register: lutris_installed
  tags: [third_party, lutris]

- name: Install Wine
  ansible.builtin.package:
    name: wine
    state: present
  when: not wine_installed.stat.exists
  become: true
  tags: [third_party, lutris]

- name: Install Lutris
  ansible.builtin.package:
    name: lutris
    state: present
  when: not lutris_installed.stat.exists
  become: true
  tags: [third_party, lutris]

- name: Install Vulkan Loader
  ansible.builtin.package:
    name:
      - vulkan-loader
      - vulkan-loader.i686
    state: present
  when: not lutris_installed.stat.exists
  become: true
  tags: [third_party, lutris]

- name: Install missing 32/64 bit libraries for Lutris
  ansible.builtin.package:
    name:
      - freetype
      - freetype.i686
      - gnutls
      - gnutls.i686
      - gnutls-devel
      - gnutls-devel.i686
      - openldap
      - openldap.i686
      - openldap-devel
      - openldap-devel.i686
      - libgpg-error
      - libgpg-error.i686
      - sqlite2.i686
      - sqlite2.x86_64
    state: present
  when: not lutris_installed.stat.exists
  become: true
  tags: [third_party, lutris]
