---
- name: Setup Chrome
  ansible.builtin.import_tasks: chrome.yml
  when: install_chrome

- name: Setup Slack
  ansible.builtin.import_tasks: slack.yml
  when: install_slack

- name: Setup Spotify
  ansible.builtin.import_tasks: spotify.yml
  when: install_spotify

- name: Setup VSCode
  ansible.builtin.import_tasks: vscode.yml
  when: install_vscode

- name: Setup Zoom Client
  ansible.builtin.import_tasks: zoom.yml
  when: install_zoom

- name: Setup Lutris
  ansible.builtin.import_tasks: lutris.yml
  when: install_lutris

- name: Setup OwnCloud
  ansible.builtin.import_tasks: owncloud.yml
  when: install_owncloud

- name: Setup Docker
  ansible.builtin.import_tasks: docker.yml
  when: install_docker

- name: Setup Google Cloud SDK
  ansible.builtin.import_tasks: gcloud-sdk.yml
  when: install_gcloud

- name: Setup Steam
  ansible.builtin.import_tasks: steam.yml
  when: install_steam

- name: Setup Auto-CPUFreq
  ansible.builtin.import_tasks: auto-cpufreq.yml
  when: install_autocpu

- name: Setup Chef
  ansible.builtin.import_tasks: chef.yml
  when: install_chef

- name: Setup Alacritty
  ansible.builtin.import_tasks: alacritty.yml
  when: install_alacritty
