---
- name: Check for fedora-spotify repo
  stat: 
    path: /etc/yum.repos.d/fedora-spotify.repo
  register: fedora_spotify_installe

- name: Install fedora-spotify repo
  command: dnf config-manager --add-repo=https://negativo17.org/repos/fedora-spotify.repo
  when: not fedora_spotify_installed.stat.exists

- name: Install Spotify
  package:
    name: spotify-client
    state: present
  ignore_errors: true
