---
- name: Check for Zoom
  ansible.builtin.stat:
    path: /usr/bin/zoom
  register: zoom_installed

- name: Install Zoom RPM
  ansible.builtin.package:
    name: https://zoom.us/client/latest/zoom_x86_64.rpm
    disable_gpg_check: true
    state: present
  when: not zoom_installed.stat.exists
