---

- name: Check for Zoom
  stat: 
    path: /usr/bin/zoom
  register: zoom_installed

- name: Install Zoom RPM
  package:
    name: 'https://zoom.us/client/latest/zoom_x86_64.rpm'
    disable_gpg_check: yes
    state: present
  when: not zoom_installed.stat.exists
    
