---
- name: Check if Zoom is installed
  ansible.builtin.shell: rpm -q zoom
  register: zoom_installed
  ignore_errors: true

- name: Install Zoom RPM
  ansible.builtin.dnf:
    name: https://zoom.us/client/latest/zoom_x86_64.rpm
    disable_gpg_check: true
    state: present
  when: zoom_installed.rc != 0
