---
- name: Check if Zoom is installed
  ansible.builtin.command: rpm -q zoom
  register: zoom_installed
  changed_when: false
  failed_when: false
  tags: [third_party, zoom]

- name: Install Zoom RPM
  ansible.builtin.dnf:
    name: https://zoom.us/client/latest/zoom_x86_64.rpm
    disable_gpg_check: true
    state: present
  when: zoom_installed.rc != 0
  become: true
  tags: [third_party, zoom]
