name: Ansible Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@4cffbd88a4b4ffdf9613107546cd6c2d6da508d8
      with:
        targets: "./"
        override-deps: |
          ansible-lint==5.3.2
        args: "-q"
